In [8]:
import pandas as pd

df = pd.read_csv("dataset/book-crossing/preprocessed/book-crossing-2024-09-09.csv")
df

C:\Users\minhh\AppData\Local\Temp\ipykernel_10900\2386795078.py:3: DtypeWarning: Columns (26) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("dataset/book-crossing/preprocessed/book-crossing-2024-09-09.csv")

,isbn,country_code,language_code,asin,is_ebook,average_rating,kindle_asin,description,format,publisher,...,book_id,ratings_count,title,title_without_series,categories,authors,publisher_backup,image_url_backup,publication_year_backup,preprocessed_description
0,0001053744,US,NaN,NaN,False,3.90,NaN,"This 14th-century poem, translated into modern...",Audiobook,HarperCollins UK,...,2654759,30,Pearl and Sir Orfeo,Pearl and Sir Orfeo,['Poetry'],J. R. R. Tolkien,Trafalgar Square Publishing,http://images.amazon.com/images/P/0001053744.0...,1999,century poem translated modern english tolkien...
1,0001821504,US,eng,NaN,False,4.13,NaN,The Adventures of Paddingtonis a special editi...,Hardcover,NaN,...,1254531,203,The Adventures of Paddington,The Adventures of Paddington,['Children'],Michael Bond,HarperCollins Publishers,http://images.amazon.com/images/P/0001821504.0...,1970,adventure paddingtonis special edition contain...
2,0001837397,US,NaN,NaN,False,4.43,B00830SQX2,Step into the exquisite miniature world of the...,Hardcover,HarperCollinsChildren'sBooks,...,529155,34,Autumn Story,Autumn Story,['Children'],Jill Barklem,William Collins Sons Co Ltd,http://images.amazon.com/images/P/0001837397.0...,0,step exquisite miniature world mouse brambly h...
3,000184251X,US,NaN,NaN,False,4.50,NaN,"Augustus Callendar, a newspaper correspondent,...",NaN,NaN,...,2596500,20,"February's Road (Callendars, Book 2)","February's Road (Callendars, Book 2)",['Children'],John Verney,HarperCollins Publishers,http://images.amazon.com/images/P/000184251X.0...,1987,augustus callendar newspaper correspondent cri...
4,0001981625,US,eng,NaN,False,3.57,NaN,Leading up to the 40th anniversary of the firs...,Hardcover,HarperCollins Publishers,...,2159572,83,The Sea Of Tranquility,The Sea Of Tranquility,['Children'],Mark Haddon,HarperCollins Publishers,http://images.amazon.com/images/P/0001981625.0...,1996,leading anniversary first moon landing excitem...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52978,9997410440,US,eng,NaN,False,3.75,NaN,"""This is a terrifying, yet inspiring novel. As...",Hardcover,Random House (NY),...,580970,51,Nine Hours to Rama,Nine Hours to Rama,"['History, Biology']",Stanley Wolpert,Random House (T),http://images.amazon.com/images/P/9997410440.0...,1962,terrifying yet inspiring novel nine fateful ho...
52979,9997412958,US,NaN,NaN,False,3.99,NaN,"Romantic tale set in 17th-century England, whe...",NaN,NaN,...,3727139,10,The White Witch,The White Witch,"['History, Biology']",Elizabeth Goudge,Putnam Pub Group (T),http://images.amazon.com/images/P/9997412958.0...,1958,romantic tale set century england cavalier str...
52980,9997531590,US,NaN,NaN,False,4.02,B018V77ID0,World's End is the first novel in Upton Sincla...,NaN,NaN,...,204390,298,World's End,World's End,"['History, Biology']",Upton Sinclair,Penguin USA (T),http://images.amazon.com/images/P/9997531590.0...,1940,world end first novel upton sinclair lanny bud...
52981,9997555627,US,eng,NaN,False,4.37,NaN,"Five-year-old Zeze lives in Rio de Janeiro, in...",Hardcover,NaN,...,46571,685,My Sweet Orange Tree,My Sweet Orange Tree,['Children'],Jose Mauro De Vasconcelos,Random House (T),http://images.amazon.com/images/P/9997555627.0...,1971,five year old zeze life rio janeiro forgotten ...
52982,9999669972,US,NaN,NaN,False,3.78,NaN,Help Me Be Good About Being Bullied explains w...,Hardcover,NaN,...,12189298,12,Being Bullied,Being Bullied,['Children'],Joy Berry,Smithmark Pub,http://images.amazon.com/images/P/9999669972.0...,1989,help good bullied explains child bully others ...

In [9]:
df = df.iloc[7:8]
df

,isbn,country_code,language_code,asin,is_ebook,average_rating,kindle_asin,description,format,publisher,...,book_id,ratings_count,title,title_without_series,categories,authors,publisher_backup,image_url_backup,publication_year_backup,preprocessed_description
7,0002113570,US,en-US,NaN,False,4.33,NaN,Valkoinen tytto simpanssien parissa viidakossa...,Hardcover,Collins,...,2657522,43,In the Shadow of Man,In the Shadow of Man,"['History, Biology']",Jane Goodall,Collins,http://images.amazon.com/images/P/0002113570.0...,1971,valkoinen tytto simpanssien parissa viidakossa...

In [12]:
import re

categories = df["categories"].values[0]
categories = re.sub(r"[^\w\s,]", "", categories)
print(categories)

History, Biology